<?php

declare(strict_types=1);

namespace Bjanczak\FilamentFlexFields\Support;

/**
 * Pinned Whisper / ONNX browser runtime (opt-in; not shipped in the Composer package).
 *
 * Hashes are SHA-256 of the @xenova/transformers dist files for the declared version.
 * Regenerated by `node scripts/build-whisper-runtime.mjs` when upgrading transformers.
 */
final class WhisperRuntimeManifest
{
    public const PACKAGE = '@xenova/transformers';

    public const VERSION = '2.17.2';

    public const INSTALL_COMMAND = 'php artisan fff:whisper:install';

    /**
     * Runtime files published to public/filament-flex-fields-assets/whisper/.
     * Source maps are intentionally excluded from customer installs.
     *
     * @var array<string, string> filename => sha256 hex
     */
    public const FILES = [
        'transformers.min.js' => 'bcf7cf304e51f470ed59409622b9d6ffbad80dfcf5baf6a40c919e4b9c4ff812',
        'ort-wasm.wasm' => 'bbdcb6b3c7d294577d806077630460be4e13ca35a345acb5e81188e9649fa74a',
        'ort-wasm-simd.wasm' => '9bd07bababc65f53d061f457233eeae501be7ceb8a2adb9eef52d87fe776d865',
        'ort-wasm-threaded.wasm' => '2ee2f715093aaacc0344bfb1610313eb49a3474e8afde5e4635f30ddfc7615c8',
        'ort-wasm-simd-threaded.wasm' => 'ac23f2f3cbd519a65a0796f7c79eb34ead4c1f6f31eb06e14ed8a9579d697ef6',
    ];

    /**
     * @return list<string>
     */
    public static function filenames(): array
    {
        return array_keys(self::FILES);
    }

    public static function sha256(string $filename): ?string
    {
        return self::FILES[$filename] ?? null;
    }

    public static function downloadUrl(string $filename): string
    {
        if (! isset(self::FILES[$filename])) {
            throw new \InvalidArgumentException("Unknown Whisper runtime file [{$filename}].");
        }

        return sprintf(
            'https://cdn.jsdelivr.net/npm/%s@%s/dist/%s',
            self::PACKAGE,
            self::VERSION,
            $filename,
        );
    }

    /**
     * @return array{package: string, version: string, files: array<string, string>}
     */
    public static function toArray(): array
    {
        return [
            'package' => self::PACKAGE,
            'version' => self::VERSION,
            'files' => self::FILES,
        ];
    }
}
