<?php

declare(strict_types=1);

namespace Bjanczak\FilamentFlexFields\Enums\FieldTypeDefaults;

use Bjanczak\FilamentFlexFields\Enums\FieldType;

final class FieldTypeDefaultConfigRegistry
{
    /**
     * @return array<string, mixed>
     */
    public static function for(FieldType $type): array
    {
        return match ($type) {
            FieldType::Integer => array_merge(self::flexTextInput(), [
                'min' => null,
                'max' => null,
                'step' => 1,
                'allow_decimals' => false,
            ]),
            FieldType::Decimal => array_merge(self::flexTextInput(), [
                'min' => null,
                'max' => null,
                'step' => 1,
            ]),
            FieldType::NumberStepper => [
                'min' => null,
                'max' => null,
                'step' => 1,
                'size' => 'md',
                'icons' => [],
                'decrement_icon' => '',
                'increment_icon' => '',
            ],
            FieldType::Currency => [
                'currency' => 'PLN',
                'locale' => 'pl_PL',
                'size' => 'md',
                'variant' => 'primary',
                'currencies' => null,
                'min' => null,
                'max' => null,
                'allow_negative' => false,
                'animated' => true,
                'commit_decimals_on_blur' => true,
                'searchable' => true,
            ],
            FieldType::Percentage => [
                'min' => 0,
                'max' => 100,
                'step' => 1,
                'show_output' => true,
                'suffix' => '%',
                'variant' => 'default',
                'size' => 'md',
                'track_label' => null,
            ],
            FieldType::RangeSlider, FieldType::RangeMinMax => [
                'min' => 0,
                'max' => 100,
                'step' => 1,
                'show_output' => true,
                'suffix' => null,
                'track_label' => null,
                'size' => 'md',
                'variant' => 'default',
            ],
            FieldType::FlexSlider => [
                'min' => 0,
                'max' => 100,
                'step' => 1,
                'is_range' => false,
                'size' => 'md',
                'variant' => 'default',
                'show_value' => true,
                'show_step_dots' => false,
                'hide_thumb_until_interaction' => false,
                'fill_track' => true,
                'value_position' => 'end',
                'prefix' => '',
                'suffix' => '',
                'track_label' => '',
                'auto_fill' => true,
                'color' => '',
                'fill_color' => '',
                'decimal_places' => 0,
            ],
            FieldType::PriceRange => [
                'min' => 0,
                'max' => 1000,
                'step' => 1,
                'prefix' => '$',
                'histogram' => [],
                'variant' => 'primary',
                'size' => 'md',
                'integer' => false,
                'decimal_places' => 0,
                'show_inputs' => true,
                'min_input_label' => '',
                'max_input_label' => '',
            ],
            FieldType::FlexTextarea => [
                'variant' => 'primary',
                'size' => 'md',
                'rows' => 3,
                'character_counter' => false,
                'animated_autosize' => true,
                'max_height' => '24rem',
                'speech_dictation' => false,
                'emoji_picker' => false,
                'footer' => '',
                'max_length' => null,
                'min_length' => null,
                'speech_dictation_language' => null,
                'emoji_picker_locale' => null,
                'submit_action' => [],
                'toolbar_selects' => [],
                'toolbar_select' => [],
            ],
            FieldType::FlexTextInput, FieldType::Email, FieldType::Url => self::flexTextInput(),
            FieldType::Slug => [
                'size' => 'md',
                'variant' => 'primary',
                'source' => null,
                'source_live' => true,
                'separator' => '-',
                'max_slug_length' => null,
                'url_host' => null,
                'url_path' => null,
                'url_host_visible' => true,
                'url_path_visible' => true,
                'permalink_preview' => true,
                'show_visit_link' => true,
                'show_copy_button' => true,
                'show_regenerate_button' => true,
                'action_button_labels' => true,
                'auto_generate' => true,
                'preserve_slug_on_edit' => true,
                'inline_editing' => true,
                'allow_homepage_slug' => false,
                'slug_unique' => true,
                'debounce' => 400,
                'translatable_locales' => null,
                'slug_source_locale' => null,
                'spatie_translatable' => false,
                'title_slug' => false,
                'title_field' => null,
                'required_title_locales' => null,
                'slug_unique_parameters' => [],
                'slug_readonly' => false,
                'slug_label_postfix' => null,
                'spatie_model' => null,
                'spatie_slug_field' => 'slug',
                'spatie_source_field' => null,
                'translatable_title_field' => null,
            ],
            FieldType::VerificationCode => [
                'length' => 6,
                'groups' => [3, 3],
                'group_separator' => '-',
                'allowed_characters' => 'numeric',
                'size' => 'md',
                'color' => 'primary',
                'auto_submit' => false,
                'auto_submit_method' => null,
                'loading' => false,
            ],
            FieldType::CreditCard => [
                'variant' => 'midnight',
                'input_variant' => 'primary',
                'size' => 'md',
                'flip_on_cvv_focus' => true,
                'mark' => '',
                'number_label' => '',
                'name_label' => '',
                'expiry_label' => '',
                'cvv_label' => '',
            ],
            FieldType::Phone => [
                'size' => 'md',
                'variant' => 'primary',
                'default_country' => 'PL',
                'countries' => null,
                'except_countries' => [],
                'searchable' => true,
                'suffix_icon' => true,
                'international_prefix' => true,
                'mobile_only' => false,
                'fixed_line_only' => false,
            ],
            FieldType::Country => [
                'size' => 'md',
                'variant' => 'primary',
                'default_country' => 'PL',
                'countries' => null,
                'except_countries' => [],
                'searchable' => true,
                'browser_locale_default' => false,
                'browser_locale_sort_first' => false,
                'show_country_code' => false,
                'show_dial_code' => false,
            ],
            FieldType::Timezone => [
                'size' => 'md',
                'variant' => 'primary',
                'default_timezone' => null,
                'timezones' => null,
                'except_timezones' => [],
                'searchable' => true,
                'show_offset' => true,
                'browser_timezone_default' => false,
                'browser_timezone_sort_first' => false,
                'prefix_icon' => null,
            ],
            FieldType::Schedule => [
                'size' => 'md',
                'variant' => 'primary',
                'days' => null,
                'timezone' => 'UTC',
                'time_step' => 5,
                'min_slots' => 1,
                'max_slots' => 10,
                'allow_copy_to_weekdays' => true,
                'copy_source_day' => 'mon',
                'workdays' => null,
                'locked_days' => [],
                'require_slots_for_enabled_days' => true,
            ],
            FieldType::Date, FieldType::Time, FieldType::DateTime, FieldType::DateRange, FieldType::Duration, FieldType::TimeRange, FieldType::Month, FieldType::Year => self::dateTime(),
            FieldType::AddressAutocomplete => array_merge(self::geocoding(), [
                'layout' => 'input',
                'fields' => ['street', 'city', 'postcode', 'country', 'country_name', 'place_name'],
                'store_format' => 'structured',
                'string_format' => '{place_name}',
                'required_fields' => [],
                'searchable' => true,
                'size' => 'md',
                'variant' => 'primary',
                'mapbox_token' => null,
                'placeholder' => null,
            ]),
            FieldType::Video => [
                'src' => '',
                'size' => 'md',
                'ratio' => '16:9',
                'full_width' => false,
                'controls_layout' => 'compact',
                'controls' => true,
                'native_controls' => false,
                'autoplay' => false,
                'loop' => false,
                'muted' => false,
                'plays_inline' => true,
                'skip_seconds' => 10,
                'picture_in_picture' => false,
                'allow_youtube' => true,
                'youtube_no_cookie' => true,
                'auto_hide_controls' => true,
                'poster' => null,
                'placeholder' => null,
                'title' => '',
                'subtitle' => '',
                'fullscreenable' => true,
                'volume_control' => true,
                'settings_menu' => false,
                'tooltips' => true,
                'castable' => false,
                'cast' => false,
                'air_playable' => false,
                'airplay' => false,
                'playback_rates' => [],
                'quality_options' => [],
                'compact_controls' => false,
            ],
            FieldType::Audio => [
                'src' => '',
                'size' => 'md',
                'full_width' => false,
                'loop' => false,
                'waveform' => null,
            ],
            FieldType::VoiceNote => [
                'size' => 'md',
                'max_duration' => 120,
                'upload_immediately' => false,
                'directory' => 'voice-notes',
            ],
            FieldType::Barcode => [
                'size' => 'md',
                'variant' => 'primary',
                'formats' => null,
                'continuous' => false,
                'beep_on_scan' => true,
                'auto_submit' => false,
                'camera_facing' => 'environment',
                'scan_delay' => 750,
                'scan_interval' => 120,
                'allow_camera_switch' => true,
                'preferred_device_id' => null,
                'store_detected_format' => false,
                'pause_when_hidden' => true,
                'allow_manual_input' => true,
                'validate_checksum' => false,
                'decode_fps' => null,
                'scan_button_label' => null,
                'modal_heading' => null,
            ],
            FieldType::MapPicker => array_merge(self::geocoding(), [
                'layout' => 'map',
                'fields' => ['lat', 'lng', 'street', 'city', 'postcode', 'country', 'place_name'],
                'store_format' => 'structured',
                'string_format' => '{place_name}',
                'required_fields' => [],
                'default_center' => [52.2297, 21.0122],
                'default_zoom' => 12,
                'searchable' => true,
                'mapbox_token' => null,
            ]),
            FieldType::SocialLinks => [
                'platforms' => [],
                'exclude_platforms' => [],
                'max_links' => null,
                'reorderable' => false,
                'auto_format_urls' => true,
                'variant' => 'primary',
                'size' => 'md',
            ],
            FieldType::TrafficSplit => [
                'segment_count' => 3,
                'size' => 'md',
                'variant' => 'default',
                'labels' => [],
                'locked_segments' => [],
                'min_weight' => 12,
                'value_threshold' => 18,
                'disabled' => false,
                'linked_repeater' => null,
                'linked_repeater_numeric_labels' => true,
                'linked_repeater_minimum_items' => 2,
            ],
            FieldType::SegmentControl => [
                'options' => [],
                'size' => 'md',
                'variant' => 'default',
                'full_width' => false,
                'separators' => true,
                'icon_only' => false,
                'expand_selected_label' => false,
                'color' => '',
                'icons' => [],
                'disabled_options' => [],
            ],
            FieldType::ChoiceCards => [
                'options' => [],
                'layout' => 'stack',
                'grid_columns' => 1,
                'indicator' => 'radio',
                'variant' => 'default',
                'size' => 'md',
                'color' => '',
                'ripple' => false,
                'disabled_options' => [],
            ],
            FieldType::ChoiceCheckboxCards => [
                'options' => [],
                'layout' => 'stack',
                'grid_columns' => 1,
                'indicator' => 'checkbox',
                'variant' => 'default',
                'size' => 'md',
                'color' => '',
                'ripple' => false,
                'min_selections' => null,
                'max_selections' => null,
                'exact_selections' => null,
                'disabled_options' => [],
            ],
            FieldType::ImageChoiceCards => [
                'options' => [],
                'multiple' => false,
                'columns' => 4,
                'indicator' => null,
                'variant' => 'default',
                'size' => 'md',
                'rounding' => 'lg',
                'color' => '',
                'image_aspect_ratio' => '3/4',
                'image_fit' => 'cover',
                'disabled_options' => [],
                'min_selections' => null,
                'max_selections' => null,
                'exact_selections' => null,
                'ripple' => false,
            ],
            FieldType::FlexChecklist => [
                'options' => [],
                'icons' => [],
                'descriptions' => [],
                'disabled_options' => [],
                'size' => 'md',
                'color' => 'primary',
                'min_selections' => null,
                'max_selections' => null,
                'exact_selections' => null,
            ],
            FieldType::FlexRadiolist => [
                'options' => [],
                'icons' => [],
                'descriptions' => [],
                'disabled_options' => [],
                'size' => 'md',
                'variant' => 'default',
                'color' => 'primary',
            ],
            FieldType::MatrixChoice => [
                'mode' => 'radio',
                'rows' => [],
                'columns' => [],
                'column_icons' => [],
                'disabled_rows' => [],
                'required_rows' => [],
                'disabled_cells' => [],
                'disable_cell_when' => [],
                'disable_row_when' => [],
                'size' => 'md',
                'color' => 'primary',
            ],
            FieldType::Toggle => [
                'variant' => 'default',
                'layout' => 'row',
                'size' => 'md',
                'label_position' => 'start',
                'inline' => false,
                'inline_with_label' => false,
                'compact' => false,
                'ripple' => false,
                'disabled' => false,
                'description' => '',
                'badge' => '',
                'badge_color' => 'primary',
                'color' => 'primary',
                'on_color' => '',
                'off_color' => '',
                'on_icon' => '',
                'off_icon' => '',
            ],
            FieldType::Select => [
                'options' => [],
                'multiple' => false,
                'searchable' => false,
                'size' => 'md',
                'variant' => 'bordered',
                'clearable' => true,
                'chip_color' => 'neutral',
                'disabled' => false,
                'keep_selected_options_in_dropdown' => false,
                'color' => '',
                'rich_options' => false,
                'option_view' => null,
                'option_trigger_view' => null,
                'rich_list_trigger_display' => false,
                'option_layout' => null,
                'inline_search' => false,
                'native' => false,
                'dropdown_align' => null,
                'chevron_icon' => null,
                'clear_icon' => null,
            ],
            FieldType::Radio, FieldType::CheckboxList => [
                'options' => [],
            ],
            FieldType::UserSelect => [
                'options' => [],
                'option_model' => null,
                'name_column' => 'name',
                'email_column' => null,
                'avatar_column' => null,
                'verification_column' => null,
                'max_visible_avatars' => 5,
                'multiple' => false,
                'searchable' => true,
            ],
            FieldType::DualListbox => [
                'options' => [],
                'variant' => 'bordered',
                'size' => 'md',
                'searchable' => true,
                'reorderable' => true,
                'move_on_double_click' => true,
                'show_transfer_buttons' => true,
                'list_height' => null,
                'available_label' => null,
                'selected_label' => null,
                'disabled_options' => [],
                'min_items' => null,
                'max_items' => null,
                'exact_items' => null,
                'icons' => [],
            ],
            FieldType::Tags => [
                'size' => 'md',
                'variant' => 'primary',
                'use_spatie_tags' => false,
                'spatie_tag_type' => null,
                'separator' => null,
                'split_keys' => ['Tab'],
                'suggestions' => [],
                'tag_prefix' => null,
                'tag_suffix' => null,
                'reorderable' => false,
                'color' => 'primary',
                'trim' => false,
                'max_tags' => null,
                'suggestions_only' => false,
                'duplicate_insensitive' => false,
                'show_tag_count' => false,
            ],
            FieldType::Rating => [
                'max' => 5,
                'size' => 'md',
                'color' => 'warning',
                'icon' => null,
                'show_value' => false,
                'read_only' => false,
            ],
            FieldType::Nps => [
                'variant' => 'pills',
                'color_coded' => false,
                'scale_max' => 10,
                'options' => [
                    ['value' => '0', 'label' => '0'],
                    ['value' => '1', 'label' => '1'],
                    ['value' => '2', 'label' => '2'],
                    ['value' => '3', 'label' => '3'],
                    ['value' => '4', 'label' => '4'],
                    ['value' => '5', 'label' => '5'],
                    ['value' => '6', 'label' => '6'],
                    ['value' => '7', 'label' => '7'],
                    ['value' => '8', 'label' => '8'],
                    ['value' => '9', 'label' => '9'],
                    ['value' => '10', 'label' => '10'],
                ],
                'min_label' => 'Not at all likely',
                'max_label' => 'Extremely likely',
                'size' => 'md',
                'rounding' => '',
                'disabled_options' => [],
                'icons' => [],
            ],
            FieldType::ColorPresets => [
                'colors' => [],
                'section_label' => null,
                'section_icon' => null,
                'size' => 'md',
                'tooltips' => false,
            ],
            FieldType::Color => [
                'colors' => [
                    '#18181b',
                    '#d946ef',
                    '#3b82f6',
                    '#22c55e',
                    '#eab308',
                    '#ffffff',
                ],
                'size' => 'md',
                'tooltips' => true,
                'section_label' => null,
                'section_icon' => null,
            ],
            FieldType::FlexColorPicker => [
                'layout' => 'advanced',
                'format' => 'hex',
                'alpha' => false,
                'eyedropper' => true,
                'grid_columns' => 12,
                'grid_rows' => 10,
                'grid_colors' => null,
                'size' => 'md',
                'variant' => 'primary',
            ],
            FieldType::File, FieldType::Image => self::fileUpload(),
            FieldType::Signature => [
                'pen_color' => '#18181b',
                'pen_width' => 2.5,
                'background_color' => '#ffffff',
                'fullscreen' => true,
                'undoable' => true,
                'max_size_kb' => 48,
                'min_strokes' => 1,
                'smoothing' => true,
                'download_format' => null,
                'download_filename' => 'signature',
                'webp_quality' => 0.9,
                'view_box_width' => null,
                'view_box_height' => null,
                'trackpad_glide' => false,
                'trackpad_glide_key' => 'd',
                'guidelines' => false,
                'read_only' => false,
                'undo_icon' => null,
                'clear_icon' => null,
                'download_icon' => null,
                'fullscreen_icon' => null,
                'close_icon' => null,
            ],
            FieldType::IconPicker => [
                'size' => 'md',
                'variant' => 'bordered',
                'sets' => [],
                'icons' => [],
                'exclude_icons' => [],
                'search_results_layout' => 'grid',
                'layout' => 'grid',
                'close_on_select' => true,
                'grid_columns' => 8,
                'preload' => false,
                'limit_per_set' => null,
                'per_page' => 50,
            ],
            FieldType::Repeater => [
                'min_items' => null,
                'max_items' => null,
            ],
            default => [],
        };
    }

    /**
     * @return array<string, mixed>
     */
    private static function flexTextInput(): array
    {
        return [
            'variant' => 'primary',
            'size' => 'md',
            'speech_dictation' => false,
            'speech_dictation_language' => null,
            'emoji_picker' => false,
            'emoji_picker_locale' => null,
            'character_counter' => false,
            'clearable' => false,
            'loading' => false,
            'validating' => false,
            'password_strength' => false,
            'verification_status' => null,
            'verification_status_icon' => null,
            'verification_status_color' => null,
            'prefix' => '',
            'suffix' => '',
            'prefix_mode' => '',
            'suffix_mode' => '',
            'prefix_icon' => '',
            'suffix_icon' => '',
            'suffix_icon_color' => '#6B7280',
            'mask_preset' => '',
            'mask' => '',
            'trim' => false,
            'read_only' => false,
            'focus_outline' => true,
            'min_length' => null,
            'max_length' => null,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private static function dateTime(): array
    {
        return [
            'size' => 'md',
            'variant' => 'primary',
            'granularity' => 'day',
            'hour_cycle' => 24,
            'time_picker' => 'segmented',
            'minute_step' => 15,
            'show_seconds' => false,
            'show_year_segment' => true,
            'month_display' => 'numeric',
            'min_value' => null,
            'max_value' => null,
            'display_format' => null,
            'storage_format' => null,
            'locale' => null,
            'time_zone' => null,
            'force_leading_zeros' => true,
            'hide_time_zone' => false,
            'hide_time_section' => false,
            'close_on_select' => true,
            'allow_same_day' => true,
            'range_separator' => ' - ',
            'first_day_of_week' => 0,
            'unavailable_dates' => [],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private static function geocoding(): array
    {
        return [
            'search_scope' => 'all',
            'search_area' => 'global',
            'countries' => [],
            'language_mode' => 'auto',
            'language' => 'en',
            'street_addresses_only' => false,
            'search_types' => [],
            'min_search_length' => 2,
            'search_debounce' => 350,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private static function fileUpload(): array
    {
        return [
            'disk' => null,
            'directory' => null,
            'visibility' => null,
            'multiple' => false,
            'max_size' => 5120,
            'max_size_kb' => 5120,
            'min_files' => null,
            'max_files' => null,
            'max_total_size_kb' => null,
            'accepted_types' => [],
            'documents_only' => false,
            'images_only' => false,
            'variant' => 'primary',
            'size' => 'md',
            'store_metadata_in' => null,
            'scoped_directory' => false,
            'optimize_images' => false,
            'max_image_width' => null,
            'max_image_height' => null,
            'allow_url_upload' => false,
            'allow_webcam_upload' => false,
            'use_spatie_media_library' => false,
            'media_collection' => null,
            'conversion' => null,
            'conversions_disk' => null,
            'responsive_images' => false,
            'custom_properties' => [],
        ];
    }
}
