<?php

declare(strict_types=1);

namespace Bjanczak\FilamentFlexFields\Enums\FieldTypeDefaults;

use Bjanczak\FilamentFlexFields\Enums\FieldType;

final class FieldTypeDefaultConfigRegistry
{
    public static function for(FieldType $type): array
    {
        return match ($type) {
            FieldType::Integer, FieldType::Decimal, FieldType::NumberStepper => [
                'min' => null,
                'max' => null,
                'step' => 1,
            ],
            FieldType::Currency => [
                'currency' => 'PLN',
                'locale' => 'pl_PL',
                'size' => 'md',
                'currencies' => null,
                'min' => null,
                'max' => null,
                'allow_negative' => false,
                'animated' => true,
                'commit_decimals_on_blur' => true,
                'searchable' => true,
            ],
            FieldType::Percentage => [
                'min' => 0,
                'max' => 100,
                'step' => 1,
            ],
            FieldType::RangeSlider, FieldType::RangeMinMax => [
                'min' => 0,
                'max' => 100,
                'step' => 1,
                'variant' => 'default',
            ],
            FieldType::FlexSlider => [
                'min' => 0,
                'max' => 100,
                'step' => 1,
                'size' => 'md',
                'variant' => 'default',
                'show_value' => true,
                'fill_track' => true,
                'value_position' => 'end',
            ],
            FieldType::PriceRange => [
                'min' => 0,
                'max' => 1000,
                'step' => 1,
                'prefix' => '$',
                'histogram' => [],
                'variant' => 'primary',
            ],
            FieldType::FlexTextarea => [
                'variant' => 'primary',
                'size' => 'md',
                'character_counter' => false,
                'animated_autosize' => true,
                'max_height' => '24rem',
            ],
            FieldType::FlexTextInput => [
                'variant' => 'primary',
                'size' => 'md',
                'speech_dictation' => false,
                'emoji_picker' => false,
                'character_counter' => false,
                'clearable' => false,
                'loading' => false,
                'password_strength' => false,
            ],
            FieldType::Slug => [
                'size' => 'md',
                'variant' => 'primary',
                'source' => null,
                'source_live' => true,
                'separator' => '-',
                'max_slug_length' => null,
                'url_host' => null,
                'url_path' => null,
                'url_host_visible' => true,
                'url_path_visible' => true,
                'permalink_preview' => true,
                'show_visit_link' => true,
                'show_copy_button' => true,
                'show_regenerate_button' => true,
                'action_button_labels' => true,
                'auto_generate' => true,
                'preserve_slug_on_edit' => true,
                'inline_editing' => true,
                'allow_homepage_slug' => false,
                'slug_unique' => true,
                'debounce' => 400,
                'translatable_locales' => null,
                'slug_source_locale' => null,
                'spatie_translatable' => false,
            ],
            FieldType::VerificationCode => [
                'length' => 6,
                'groups' => [3, 3],
                'group_separator' => '-',
                'allowed_characters' => 'numeric',
                'size' => 'md',
                'color' => 'primary',
                'auto_submit' => false,
                'loading' => false,
            ],
            FieldType::CreditCard => [
                'variant' => 'midnight',
                'input_variant' => 'primary',
                'size' => 'md',
                'flip_on_cvv_focus' => true,
            ],
            FieldType::Phone => [
                'size' => 'md',
                'variant' => 'primary',
                'default_country' => 'PL',
                'countries' => null,
                'except_countries' => [],
                'searchable' => true,
                'suffix_icon' => true,
                'international_prefix' => true,
                'mobile_only' => false,
                'fixed_line_only' => false,
            ],
            FieldType::Country => [
                'size' => 'md',
                'variant' => 'primary',
                'default_country' => 'PL',
                'countries' => null,
                'except_countries' => [],
                'searchable' => true,
                'browser_locale_default' => false,
                'browser_locale_sort_first' => false,
                'show_country_code' => false,
                'show_dial_code' => false,
            ],
            FieldType::Timezone => [
                'size' => 'md',
                'variant' => 'primary',
                'default_timezone' => null,
                'timezones' => null,
                'except_timezones' => [],
                'searchable' => true,
                'show_offset' => true,
                'browser_timezone_default' => false,
                'browser_timezone_sort_first' => false,
            ],
            FieldType::Date, FieldType::Time, FieldType::DateTime, FieldType::DateRange, FieldType::Duration, FieldType::TimeRange, FieldType::Month, FieldType::Year => [
                'size' => 'md',
                'variant' => 'primary',
                'granularity' => 'day',
                'hour_cycle' => 24,
                'time_picker' => 'segmented',
                'minute_step' => 15,
                'show_seconds' => false,
                'min_value' => null,
                'max_value' => null,
                'display_format' => null,
                'storage_format' => null,
                'locale' => null,
                'time_zone' => null,
                'force_leading_zeros' => true,
                'hide_time_zone' => false,
                'hide_time_section' => false,
                'close_on_select' => true,
                'allow_same_day' => true,
                'range_separator' => ' - ',
                'first_day_of_week' => 0,
            ],
            FieldType::AddressAutocomplete => [
                'fields' => ['street', 'city', 'postcode', 'country', 'country_name', 'place_name'],
                'store_format' => 'structured',
                'string_format' => '{place_name}',
                'required_fields' => [],
                'searchable' => true,
                'countries' => null,
                'language' => 'pl',
                'size' => 'md',
                'variant' => 'primary',
                'street_addresses_only' => false,
                'search_types' => null,
            ],
            FieldType::Video => [
                'size' => 'md',
                'ratio' => '16:9',
                'full_width' => false,
                'controls_layout' => 'default',
                'controls' => true,
                'native_controls' => false,
                'autoplay' => false,
                'loop' => false,
                'muted' => false,
                'plays_inline' => true,
                'skip_seconds' => 10,
                'picture_in_picture' => false,
                'allow_youtube' => true,
                'youtube_no_cookie' => true,
                'auto_hide_controls' => true,
            ],
            FieldType::Audio => [
                'size' => 'md',
                'full_width' => false,
                'loop' => false,
                'waveform' => null,
            ],
            FieldType::MapPicker => [
                'fields' => ['lat', 'lng', 'street', 'city', 'postcode', 'country', 'place_name'],
                'store_format' => 'structured',
                'string_format' => '{place_name}',
                'required_fields' => [],
                'default_center' => [52.2297, 21.0122],
                'default_zoom' => 12,
                'searchable' => true,
                'countries' => null,
                'street_addresses_only' => false,
                'search_types' => null,
            ],
            FieldType::TrafficSplit => [
                'segment_count' => 3,
                'min_weight' => 12,
                'value_threshold' => 18,
                'variant' => 'default',
            ],
            FieldType::SegmentControl => [
                'options' => [],
                'variant' => 'default',
                'full_width' => false,
            ],
            FieldType::ChoiceCards => [
                'options' => [],
                'layout' => 'stack',
                'grid_columns' => 1,
                'indicator' => 'radio',
                'variant' => 'default',
            ],
            FieldType::ChoiceCheckboxCards => [
                'options' => [],
                'layout' => 'stack',
                'grid_columns' => 1,
                'indicator' => 'checkbox',
                'variant' => 'default',
                'min_selections' => null,
                'max_selections' => null,
                'exact_selections' => null,
            ],
            FieldType::FlexChecklist => [
                'options' => [],
                'icons' => [],
                'descriptions' => [],
                'disabled_options' => [],
                'size' => 'md',
                'min_selections' => null,
                'max_selections' => null,
                'exact_selections' => null,
            ],
            FieldType::FlexRadiolist => [
                'options' => [],
                'icons' => [],
                'descriptions' => [],
                'disabled_options' => [],
                'size' => 'md',
                'variant' => 'default',
            ],
            FieldType::MatrixChoice => [
                'mode' => 'radio',
                'rows' => [],
                'columns' => [],
                'column_icons' => [],
                'disabled_rows' => [],
                'required_rows' => [],
                'disabled_cells' => [],
                'disable_cell_when' => [],
                'disable_row_when' => [],
                'size' => 'md',
                'color' => 'primary',
            ],
            FieldType::Toggle => [
                'variant' => 'default',
                'layout' => 'row',
                'inline' => false,
            ],
            FieldType::Select, FieldType::MultiSelect, FieldType::Radio, FieldType::CheckboxList => [
                'options' => [],
            ],
            FieldType::UserSelect => [
                'options' => [],
                'option_model' => null,
                'name_column' => 'name',
                'email_column' => null,
                'avatar_column' => null,
                'verification_column' => null,
                'max_visible_avatars' => 5,
                'multiple' => false,
                'searchable' => true,
            ],
            FieldType::DualListbox => [
                'options' => [],
                'variant' => 'bordered',
                'size' => 'md',
                'searchable' => true,
                'reorderable' => true,
                'move_on_double_click' => true,
                'show_transfer_buttons' => true,
            ],
            FieldType::Tags => [
                'size' => 'md',
                'variant' => 'primary',
                'use_spatie_tags' => false,
                'spatie_tag_type' => null,
                'separator' => null,
                'split_keys' => ['Tab'],
                'suggestions' => [],
                'tag_prefix' => null,
                'tag_suffix' => null,
                'reorderable' => false,
                'color' => 'primary',
                'trim' => false,
                'max_tags' => null,
                'suggestions_only' => false,
                'duplicate_insensitive' => false,
                'show_tag_count' => false,
            ],
            FieldType::Rating => [
                'max' => 5,
            ],
            FieldType::ColorPresets => [
                'colors' => [],
                'section_label' => null,
                'section_icon' => null,
                'size' => 'md',
                'tooltips' => false,
            ],
            FieldType::FlexColorPicker => [
                'layout' => 'advanced',
                'format' => 'hex',
                'alpha' => false,
                'eyedropper' => true,
                'grid_columns' => 12,
                'grid_rows' => 10,
                'grid_colors' => null,
                'size' => 'md',
            ],
            FieldType::File, FieldType::Image => [
                'max_size' => 5120,
                'accepted_types' => [],
            ],
            FieldType::Repeater => [
                'min_items' => null,
                'max_items' => null,
            ],
            default => [],
        };
    }
}
